# Raspberry Pi 4 example profile

# Change those
LUKS_PASSWORD='changeme'
ROOT_PASSWORD='changeme'

# Other settings
TARGET_IMAGE='rpi4-luks-trixie.img'
BUILD_LOG='rpi4-luks-trixie.log'
DEBOOTSTRAP_SUITE='trixie' # Tested with 'trixie', but *may* work with others
LUKS_DEV='cryptroot'
LUKS_FORMAT_ARGS='--iter-time 2000 --hash sha256 --key-size 256 --pbkdf=argon2id --cipher=xchacha20,aes-adiantum-plain64'
# Only from debian.org repo:
DEBOOTSTRAP_PACKAGES+='raspi-firmware,cryptsetup,cryptsetup-initramfs,initramfs-tools,zstd,locales,console-setup,netbase,'
# From both debian.org and raspberrypi.com repos:
RPI_PACKAGES+='linux-image-rpi-v8 linux-headers-rpi-v8 '                                                # Kernels and headers
RPI_PACKAGES+='raspi-utils rpi-update rpi-eeprom rpifwcrypto raspi-config raspberrypi-archive-keyring ' # Raspberry Pi packages
RPI_PACKAGES+='firmware-brcm80211 firmware-realtek firmware-mediatek '                                  # Firmware
RPI_PACKAGES+='systemd-timesyncd ssh sudo parted curl ntfs-3g network-manager wireguard-tools file '    # System stuff
RPI_PACKAGES+='zip unzip unrar xz-utils '                                                               # More system stuff
# RPI_PACKAGES+='dropbear dropbear-initramfs '                                                            # For remote LUKS unlock
